import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncUserEntity1771403738826 implements MigrationInterface {
    name = 'SyncUserEntity1771403738826'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1bbd34899b8e74ef2a7f3212806"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_80e310e761f458f272c20ea6add"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_112900b46aa94e7c5a2bf1db66d"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_8d3bc8b8b1eb2772cd919470810"`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "column_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "assignee_id" uuid, "creator_id" uuid NOT NULL, "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'medium', "due_date" date, "position" integer NOT NULL DEFAULT '0', "progress_percentage" numeric(5,2) NOT NULL DEFAULT '0', "total_time_logged" integer NOT NULL DEFAULT '0', "is_overdue" boolean NOT NULL DEFAULT false, "deleted_by" uuid, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_707cfc415c7c12d38dfc2ec8eb" ON "tasks" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_68d6a27df9f5cc119cac1df190" ON "tasks" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4cb489461bc751498a2885235" ON "tasks" ("creator_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_855d484825b715c545349212c7" ON "tasks" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_986f14173dba32448f3f3abb1c" ON "tasks" ("column_id") `);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_entry_type_enum" AS ENUM('timer', 'manual')`);
        await queryRunner.query(`CREATE TABLE "time_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "user_id" uuid NOT NULL, "duration_seconds" integer NOT NULL DEFAULT '0', "description" text, "entry_type" "public"."time_entries_entry_type_enum" NOT NULL DEFAULT 'manual', "started_at" TIMESTAMP, "ended_at" TIMESTAMP, "logged_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b8bc5f10269ba2fe88708904aa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1668577f1fb0024e418c9159c9" ON "time_entries" ("logged_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f16c3c269283ee42429d09d693" ON "time_entries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_104aa11ede7c8d5afbbe1fdbb2" ON "time_entries" ("task_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('active', 'completed', 'archived')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying(255) NOT NULL, "description" text, "owner_id" uuid NOT NULL, "deadline" date, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'active', "completion_percentage" numeric(5,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11b52372ea51f9159efe2402d9" ON "projects" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a27865a7be17886e3088f4a650" ON "projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1bd2fbf5d0ef67319c91acb5c" ON "projects" ("owner_id") `);
        await queryRunner.query(`CREATE TABLE "labels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying(50) NOT NULL, "color" character varying(7) NOT NULL DEFAULT '#808080', "is_system" boolean NOT NULL DEFAULT true, "project_id" uuid, CONSTRAINT "PK_c0c4e97f76f1f3a268c7a70b925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2471ffe20434e816bee71aad5e" ON "labels" ("is_system") `);
        await queryRunner.query(`CREATE INDEX "IDX_68b0da461f6765824f6db642f1" ON "labels" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "task_labels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "label_id" uuid NOT NULL, CONSTRAINT "PK_72402f2c22ceabc2e73b718c321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09dd3f6f9d04063726c498155f" ON "task_labels" ("label_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d46d4e476e3f6f8bf272b2bc1e" ON "task_labels" ("task_id", "label_id") `);
        await queryRunner.query(`CREATE TABLE "sub_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "completed" boolean NOT NULL DEFAULT false, "position" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0028874355f68f2ed21a89c2faf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_792ee7ce1185d58b0f8b424d20" ON "sub_tasks" ("task_id", "position") `);
        await queryRunner.query(`CREATE INDEX "IDX_be4002db4cc6e2d20577f48ddf" ON "sub_tasks" ("task_id") `);
        await queryRunner.query(`CREATE TYPE "public"."project_members_role_enum" AS ENUM('owner', 'member')`);
        await queryRunner.query(`CREATE TYPE "public"."project_members_invitation_status_enum" AS ENUM('pending', 'accepted', 'declined')`);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."project_members_role_enum" NOT NULL DEFAULT 'member', "invitation_status" "public"."project_members_invitation_status_enum" NOT NULL DEFAULT 'accepted', "invitation_token" character varying(255), "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "invited_by" uuid, CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bde9d5863d841afbd6f81d9908" ON "project_members" ("invitation_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_e89aae80e010c2faa72e6a49ce" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b3f491d3a3f986106d281d8eb4" ON "project_members" ("project_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('task_assigned', 'due_date_reminder', 'status_change', 'comment_mention', 'new_comment', 'invitation')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "link" text, "related_task_id" uuid, "related_project_id" uuid, "is_read" boolean NOT NULL DEFAULT false, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), "read_at" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_af08fad7c04bb85403970afdc1" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "author_id" uuid NOT NULL, "text" text NOT NULL, "parent_comment_id" uuid, "mentions" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93ce08bdbea73c0c7ee673ec35" ON "comments" ("parent_comment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d38899c31997c45d128a8973" ON "comments" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18c2493067c11f44efb35ca0e0" ON "comments" ("task_id") `);
        await queryRunner.query(`CREATE TABLE "columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "project_id" uuid NOT NULL, "title" character varying(100) NOT NULL, "position" integer NOT NULL DEFAULT '0', "wip_limit" integer, CONSTRAINT "PK_4ac339ccbbfed1dcd96812abbd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e14ed1dd284c4135e5f42ad2ae" ON "columns" ("project_id", "position") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad83764ca1d841f43830f93b78" ON "columns" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "task_id" uuid NOT NULL, "uploaded_by" uuid NOT NULL, "file_name" character varying(255) NOT NULL, "file_url" text NOT NULL, "file_size" integer NOT NULL DEFAULT '0', "file_type" character varying(50) NOT NULL, CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e25812e3fd9b3f3edf11b2c5d5" ON "attachments" ("uploaded_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_e62fd181b97caa6b150b09220b" ON "attachments" ("task_id") `);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid NOT NULL, "project_id" uuid, "task_id" uuid, "action_type" character varying(50) NOT NULL, "description" text NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fa31efc2a0bc0b517b9f7225d" ON "activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_300e98d0bf7b02d33e952ad050" ON "activity_logs" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3baa1aae6f896f72eafbdd057e" ON "activity_logs" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d54f841fa5478e4734590d4403" ON "activity_logs" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "social_login_type"`);
        await queryRunner.query(`DROP TYPE "public"."users_social_login_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "device_fcm_tokens"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "remember_me"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "features" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "features" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "job_title" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profile_photo_url" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verification_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_reset_expires" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "google_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "notification_preferences" jsonb NOT NULL DEFAULT '{"push": true, "email": true, "emailDigest": "daily"}'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_active_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255)`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'owner', 'member')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'member'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`DROP TYPE "public"."users_is_active_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_0bd5012aeb82628e07f6a1be53" ON "users" ("google_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_f4cb489461bc751498a28852356" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_551d4faac455eaad46f482d8cd4" FOREIGN KEY ("deleted_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_104aa11ede7c8d5afbbe1fdbb24" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_68b0da461f6765824f6db642f12" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_labels" ADD CONSTRAINT "FK_844df22351eb86c33c3e8c132f4" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_labels" ADD CONSTRAINT "FK_09dd3f6f9d04063726c498155f2" FOREIGN KEY ("label_id") REFERENCES "labels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_tasks" ADD CONSTRAINT "FK_be4002db4cc6e2d20577f48ddf3" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_7fb7f06d86f261a4961f145655e" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_c20d7d32d57fb098afde8be7701" FOREIGN KEY ("related_task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_b0e787f81c02ecce76b28f2efa0" FOREIGN KEY ("related_project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_18c2493067c11f44efb35ca0e03" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a" FOREIGN KEY ("parent_comment_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "columns" ADD CONSTRAINT "FK_ad83764ca1d841f43830f93b787" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e62fd181b97caa6b150b09220b1" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_300e98d0bf7b02d33e952ad0508" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_300e98d0bf7b02d33e952ad0508"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e62fd181b97caa6b150b09220b1"`);
        await queryRunner.query(`ALTER TABLE "columns" DROP CONSTRAINT "FK_ad83764ca1d841f43830f93b787"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_18c2493067c11f44efb35ca0e03"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_b0e787f81c02ecce76b28f2efa0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_c20d7d32d57fb098afde8be7701"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_7fb7f06d86f261a4961f145655e"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "sub_tasks" DROP CONSTRAINT "FK_be4002db4cc6e2d20577f48ddf3"`);
        await queryRunner.query(`ALTER TABLE "task_labels" DROP CONSTRAINT "FK_09dd3f6f9d04063726c498155f2"`);
        await queryRunner.query(`ALTER TABLE "task_labels" DROP CONSTRAINT "FK_844df22351eb86c33c3e8c132f4"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_68b0da461f6765824f6db642f12"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_104aa11ede7c8d5afbbe1fdbb24"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_551d4faac455eaad46f482d8cd4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_f4cb489461bc751498a28852356"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd5012aeb82628e07f6a1be53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`CREATE TYPE "public"."users_is_active_enum" AS ENUM('1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" "public"."users_is_active_enum" NOT NULL DEFAULT '1'`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT '2'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_active_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "notification_preferences"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "google_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_expires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_reset_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profile_photo_url"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "job_title"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "features" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "features" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD "remember_me" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "device_fcm_tokens" jsonb DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "image" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."users_social_login_type_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "social_login_type" "public"."users_social_login_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d54f841fa5478e4734590d4403"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3baa1aae6f896f72eafbdd057e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_300e98d0bf7b02d33e952ad050"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa31efc2a0bc0b517b9f7225d"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e62fd181b97caa6b150b09220b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e25812e3fd9b3f3edf11b2c5d5"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad83764ca1d841f43830f93b78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e14ed1dd284c4135e5f42ad2ae"`);
        await queryRunner.query(`DROP TABLE "columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18c2493067c11f44efb35ca0e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d38899c31997c45d128a8973"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93ce08bdbea73c0c7ee673ec35"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af08fad7c04bb85403970afdc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3f491d3a3f986106d281d8eb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e89aae80e010c2faa72e6a49ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bde9d5863d841afbd6f81d9908"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TYPE "public"."project_members_invitation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."project_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be4002db4cc6e2d20577f48ddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_792ee7ce1185d58b0f8b424d20"`);
        await queryRunner.query(`DROP TABLE "sub_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d46d4e476e3f6f8bf272b2bc1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09dd3f6f9d04063726c498155f"`);
        await queryRunner.query(`DROP TABLE "task_labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68b0da461f6765824f6db642f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2471ffe20434e816bee71aad5e"`);
        await queryRunner.query(`DROP TABLE "labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1bd2fbf5d0ef67319c91acb5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a27865a7be17886e3088f4a650"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11b52372ea51f9159efe2402d9"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_104aa11ede7c8d5afbbe1fdbb2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f16c3c269283ee42429d09d693"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1668577f1fb0024e418c9159c9"`);
        await queryRunner.query(`DROP TABLE "time_entries"`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_entry_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_986f14173dba32448f3f3abb1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_855d484825b715c545349212c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4cb489461bc751498a2885235"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68d6a27df9f5cc119cac1df190"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_707cfc415c7c12d38dfc2ec8eb"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_8d3bc8b8b1eb2772cd919470810" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_112900b46aa94e7c5a2bf1db66d" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_80e310e761f458f272c20ea6add" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1bbd34899b8e74ef2a7f3212806" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
